### ISSUE TITLE
install_osx error

### ISSUE THREAD

**Issue by pmarsceill** [smt/dotfiles#1]
Hey @smt getting this when running `install_osx`

```
Stowing ansible
atom
bin
emacs
fish
git
irc
js
ledger
mail
mongodb
newsbeuter
ranger
ruby
tmux
todo
utils
vim...
Unsuccessful stat on filename containing newline at /usr/local/Cellar/stow/2.2.2//Library/Perl/5.18/Stow.pm line 294, <DATA> line 22.
stow: ERROR: The stow directory .dotfiles does not contain package ansible
atom
bin
emacs
fish
git
irc
js
ledger
mail
mongodb
newsbeuter
ranger
ruby
tmux
todo
utils
vim
```

Should I manually install ansible to fix this?

**Comment by pmarsceill** [comment]
Closing this bc i don't care anymore.

**Comment by smt** [comment]
@pmarsceill Apologies, didn't notice this.

I'm slowly updating pieces of this, one at a time, using a Makefile rather than a shell script, as @jamestomasino does in [his dotfiles](https://github.com/jamestomasino/dotfiles).
